### PR TITLE
Fix dates not being parsed properly

### LINKED ISSUE #270: opendate not parsed properly

### PR DESCRIPTION
**Pull request by remo5000**
### Features
- momentJS is used to parse Dates
  - The key problem is that although the `Date` object works, there is some inconsistency in how browsers use them. It also is erroneous in some cases, but I'm not too familiar with this particular date format to verify.

### Issues fixed
Fixes #270 

### TODO
- [x] Specify the ISO 8601 requirement in documentation

### CODE REVIEW

**Comment by indocomsoft** [comment]
Working for the close-dates.

File: src/utils/dateHelpers.ts [hunk 1]
```diff
@@ -1,28 +1,28 @@
...
+ * @param {string} d an ISO 8601 compliant date string
  *   e.g 2018-07-06T10:20:09.961Z
  * @returns {string} A user-friendly readable date string,
  *   e.g 07/06, 20:09
  */
 export const getPrettyDate = (d: string): string => {
-  const date = new Date(d)
-  return `${date.getDate()}/${date.getMonth()}, ${date.getHours()}:${date.getMinutes()}`
+  const date = moment(d)
+  return date.format('DD/M, HH:mm')
```
Comment (ningyuansg) [inline src/utils/dateHelpers.ts]: Can we have something more human readable?

File: src/utils/dateHelpers.ts [hunk 2]
```diff
@@ -1,28 +1,28 @@
...
+ * @param {string} d an ISO 8601 compliant date string
  *   e.g 2018-07-06T10:20:09.961Z
  * @returns {boolean} true if the date specified by the paramter
  *   is before the time of execution of this function.
  */
 export const beforeNow = (d: string): boolean => {
-  const date = new Date(d)
-  const now = new Date()
-  return date <= now
+  return moment(d).isBefore(moment())
```
Comment (ningyuansg) [inline src/utils/dateHelpers.ts]: I don't think we were aware of this earlier, but backend sends us overviews even for all assessments, even those that are not yet open.

For these 'pending' assessment overviews, we need to place them in their own collapsible category, and hide their 'attempt' buttons (but we should not hide the attempt buttons for staff and admins https://github.com/source-academy/cadet/pull/195). Can you implement this change in this PR?

**Comment by remo5000** [comment]
@ningyuansg implemented it, please take a look as I'm not completely of the semantics of showing the cards

File: src/components/assessment/index.tsx [hunk 3]
```diff
@@ -132,7 +166,8 @@ class Assessment extends React.Component<IAssessmentProps, State> {
         ) : null
       display = (
         <>
-          {openCardsCollapsible}
+          {unopenedCardsCollapsible}
```
Comment (ningyuansg) [inline src/components/assessment/index.tsx]: Would prefer 'upcoming', or 'pending'.

File: src/utils/dateHelpers.ts [hunk 4]
```diff
@@ -22,7 +24,8 @@ export const beforeNow = (d: string): boolean => {
  * @returns {string} A user-friendly readable date string,
  *   e.g 07/06, 20:09
  */
-export const getPrettyDate = (d: string): string => {
-  const date = moment(d)
-  return date.format('DD/M, HH:mm')
+export const getPrettyDate = (dateString: string): string => {
+  const date = moment(dateString)
+  const prettyDate = date.format('DD/M, HH:mm')
```
Comment (ningyuansg) [inline src/utils/dateHelpers.ts]: With 07/06 it is not immediately obvious if we're talking 7th June or 6th July. Can we have the full month name?

File: src/components/assessment/__tests__/index.tsx [hunk 5]
```diff
@@ -12,6 +12,7 @@ const defaultProps: IAssessmentProps = {
   assessmentOverviews: undefined,
   handleAssessmentOverviewFetch: () => {},
   handleSubmitAssessment: (id: number) => {},
+  isStudent: false,
```
Comment (ningyuansg) [inline src/components/assessment/__tests__/index.tsx]: Should write a test for both `isStudent` values, and make sure that the button does not render for students.

File: src/components/assessment/index.tsx (hunk 3 above)
Comment (ningyuansg) [reply src/components/assessment/index.tsx]: Even 'future' is ok

File: src/utils/dateHelpers.ts (hunk 4 above)
Comment (remo5000) [reply src/utils/dateHelpers.ts]: Oh, that's what you meant!

File: src/components/assessment/__tests__/index.tsx (hunk 5 above)
Comment (remo5000) [reply src/components/assessment/__tests__/index.tsx]: Yep, sounds good

Comment (remo5000) [reply src/components/assessment/__tests__/index.tsx]: Default is `false`, so I added a test for when the user is a student

File: src/utils/dateHelpers.ts (hunk 4 above)
Comment (remo5000) [reply src/utils/dateHelpers.ts]: Now it'll show "7th June, HH:MM". I think HHMM is good because there is less ambiguity regarding AM/PM

File: src/components/assessment/index.tsx (hunk 3 above)
Comment (remo5000) [reply src/components/assessment/index.tsx]: Used upcoming

**Comment by remo5000** [comment]
@ningyuansg Do let me know if there are any further changes
